version: 2    

jobs:

  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm cit

  # Publish the module to npm
  publish:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Authenticate with npm
          command: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ${HOME}/.npmrc
      - run:
          name: Publish to npm
          command: npm version

# Circle workflows
workflows:
  version: 2
  test-and-publish:
    jobs:
      - test:
          filters:
            tags:
              only: /v.*/
      - publish:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
